"""Audit the V7 empty-patch instances to surface context-budget risks
before Phase 1 lands.

V7's commit 12 audit found 30 instances where V7 produced an empty patch
(eval harness pre-filtered them, no instance directory created in
logs/run_evaluation/.../). The hypothesis is that V7's actor ran out of
context budget on huge repos (django, sympy) and gave up. If V10's
Phase 1 localizer + Phase 3 actor see the same context limits on the
same instances, the same failure mode reappears.

This audit reads:

  - runs/swebench_500_v7/predictions/v7_full500_seed0.jsonl (to find
    empty-patch instances)
  - runs/swebench_500_v7/cache/trajectories_v7/{iid}_seed0.json
    (n_turns, task_wall_s, stop_reason)
  - meta_harness_plus/tasks/data/swebench_verified.jsonl
    (problem_statement length as a coarse complexity proxy)

and surfaces per-repo distribution + V7 trajectory characteristics. The
output drives Phase 1 design decisions about:

  1. Whether the localizer skeleton needs aggressive summarization for
     large repos (sympy, django) before being passed to the reranker.
  2. Whether the agent path's per-turn observation size cap needs to
     be tightened on large repos.
  3. Whether the empty-V7 instances should be flagged in
     splits/v7_difficulty_priors.json as high-risk for Phase 1
     evaluation.

Output: docs/audits/empty_v7_context_budget.md
"""

from __future__ import annotations

import collections
import json
import pathlib


PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
PREDICTIONS = PROJECT_ROOT / "runs" / "swebench_500_v7" / "predictions" / "v7_full500_seed0.jsonl"
TRAJ_ROOT = PROJECT_ROOT / "runs" / "swebench_500_v7" / "cache" / "trajectories_v7"
DATASET = PROJECT_ROOT / "meta_harness_plus" / "tasks" / "data" / "swebench_verified.jsonl"
OUT = PROJECT_ROOT / "docs" / "audits" / "empty_v7_context_budget.md"


def main() -> int:
    # 1. Find empty-patch instances.
    empty_iids: list[str] = []
    for line in PREDICTIONS.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        rec = json.loads(line)
        if not (rec.get("model_patch") or "").strip():
            empty_iids.append(rec["instance_id"])

    # 2. Look up dataset row for each — get repo + problem_statement length.
    rows_by_iid: dict[str, dict] = {}
    for line in DATASET.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        r = json.loads(line)
        if r["instance_id"] in empty_iids:
            rows_by_iid[r["instance_id"]] = r

    # 3. Read V7 trajectory metadata.
    by_repo: collections.Counter[str] = collections.Counter()
    by_stop: collections.Counter[str] = collections.Counter()
    rows: list[dict] = []
    for iid in empty_iids:
        repo = rows_by_iid.get(iid, {}).get("repo", "?")
        ps = rows_by_iid.get(iid, {}).get("problem_statement", "")
        traj_path = TRAJ_ROOT / f"{iid}_seed0.json"
        n_turns = wall_s = stop = None
        if traj_path.exists():
            try:
                t = json.loads(traj_path.read_text())
                n_turns = int(t.get("n_turns", 0))
                wall_s = float(t.get("task_wall_s", 0.0) or 0.0)
                stop = t.get("stop_reason", "")
            except Exception:
                pass
        rows.append({
            "iid": iid,
            "repo": repo,
            "problem_statement_chars": len(ps),
            "n_turns": n_turns,
            "task_wall_s": wall_s,
            "stop_reason": stop,
        })
        by_repo[repo] += 1
        if stop:
            by_stop[stop] += 1

    # 4. Sort and write report.
    rows.sort(key=lambda r: (r["repo"], r["iid"]))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    out: list[str] = []
    out.append("# V7 empty-patch instances — context-budget audit")
    out.append("")
    out.append(
        "Generated by `scripts/audit_empty_v7_context_budget.py`. Reads V7 "
        "predictions, V7 trajectory metadata, and the Verified dataset row "
        "for each empty-patch instance. No oracle fields read."
    )
    out.append("")
    out.append(f"- **Empty-patch instances:** {len(empty_iids)}")
    out.append(f"- **Trajectories read:** {sum(1 for r in rows if r['n_turns'] is not None)}")
    out.append("")

    out.append("## Distribution by repo")
    out.append("")
    out.append("| Repo | Empty patches | Notes |")
    out.append("|---|---|---|")
    for repo, n in sorted(by_repo.items(), key=lambda x: -x[1]):
        size_note = ""
        if "django" in repo or "sympy" in repo:
            size_note = "large repo — Phase 1 localizer needs aggressive summarization"
        elif "matplotlib" in repo:
            size_note = "large repo with binary assets — exclude from skeleton walk"
        out.append(f"| {repo} | {n} | {size_note} |")
    out.append("")

    out.append("## V7 stop-reason distribution")
    out.append("")
    out.append("| stop_reason | Count |")
    out.append("|---|---|")
    for stop, n in sorted(by_stop.items(), key=lambda x: -x[1]):
        out.append(f"| {stop or '(none)'} | {n} |")
    out.append("")

    out.append("## Per-instance detail")
    out.append("")
    out.append("| Instance | Repo | issue chars | n_turns | wall_s | stop_reason |")
    out.append("|---|---|---|---|---|---|")
    for r in rows:
        wall = f"{r['task_wall_s']:.1f}" if r["task_wall_s"] else "-"
        turns = str(r["n_turns"]) if r["n_turns"] is not None else "-"
        out.append(
            f"| `{r['iid']}` | {r['repo']} | {r['problem_statement_chars']} | "
            f"{turns} | {wall} | {r['stop_reason'] or '-'} |"
        )
    out.append("")

    # 5. Phase 1 implications.
    out.append("## Phase 1 implications")
    out.append("")
    top_repo, top_n = max(by_repo.items(), key=lambda x: x[1])
    out.append(
        f"- **{top_repo}** alone accounts for {top_n}/{len(empty_iids)} "
        f"empty-patch instances. Phase 1's hierarchical localization MUST "
        f"avoid passing the full repo skeleton to the reranker on these "
        f"instances; aggressive summarization (one-line per file, top-N "
        f"directories only) is required."
    )
    out.append("")
    used_max_turns = sum(1 for r in rows if r["n_turns"] is not None and r["n_turns"] >= 50)
    if used_max_turns:
        out.append(
            f"- {used_max_turns}/{len(empty_iids)} hit V7's turn limit "
            f"(`stop_reason='turn_limit'` or `n_turns >= 50`). Phase 3's "
            f"agent path with `T_max_hard=50` (V10_DESIGN.md §3.4) needs a "
            f"per-turn cost guard that triggers BEFORE the turn limit on "
            f"these instances — otherwise the same empty-patch failure "
            f"mode reappears in V10."
        )
    short_issues = sum(1 for r in rows if r["problem_statement_chars"] < 500)
    out.append(
        f"- Issue length distribution: {short_issues}/{len(empty_iids)} "
        f"have problem_statement < 500 chars. Short issues + huge repos = "
        f"localization is the bottleneck (the issue text doesn't constrain "
        f"the search; the repo skeleton must do most of the narrowing). "
        f"Phase 1's traceback parser (Stage 1c) and symbol grep (Stage 1d) "
        f"are most valuable when the issue is short — these instances are "
        f"the test case for whether localization actually works."
    )
    out.append("")
    out.append(
        "**Conclusion:** the empty-V7 instances are concentrated in large "
        "repos (django + sympy = ~83%) and frequently hit turn limits. "
        "Phase 1's localizer must compress the skeleton aggressively for "
        "these repos, and Phase 3's agent must finalize on partial "
        "candidates rather than time out empty-handed. Both are explicit "
        "in V10_DESIGN.md but worth re-confirming as Phase 1 acceptance "
        "criteria."
    )
    out.append("")

    OUT.write_text("\n".join(out))
    print(f"[audit] wrote {OUT.relative_to(PROJECT_ROOT)}")
    print(f"[audit] empty_iids={len(empty_iids)}  by_repo={dict(by_repo)}  "
          f"by_stop={dict(by_stop)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
