"""SWE-bench Pro 5-instance retrieval smoke (Step 5 acceptance).

Confirms the existing Phase 1 retrieval pipeline (Stage 1b, BM25-only,
no embedding/traceback/rerank) runs cleanly on Pro instances. Validates:

  - load_pro_views projects Pro rows into clean InstanceViews.
  - Sandbox starts the ``jefzda/sweap-images:{tag}`` image based on
    view.dockerhub_tag (the new field).
  - run_stage_1b_retrieval reads files from /testbed, indexes BM25,
    returns candidates without firewall errors.

This is NOT a benchmark — no scoring against gold patches (eval.py is
Verified-only at the moment; Pro evaluation infra lands later). It's a
plumbing test: the dataset adapter and Sandbox path work on Pro shape.
"""

from __future__ import annotations

import json
import pathlib
import sys
import time


PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
SPLIT = PROJECT_ROOT / "splits" / "test_pro.json"
OUT = PROJECT_ROOT / "docs" / "audits" / "pro_5instance_smoke.md"


def _smoke_5_instances() -> int:
    """Run Stage 1b retrieval (BM25 only) on the first 5 Pro instances
    that have local images present."""
    from harness.dataset import load_pro_views
    from harness.retrieval import run_stage_1b_retrieval
    from harness.sandbox import Sandbox

    data = json.loads(SPLIT.read_text())
    # Pick 5 instances; skip those whose image isn't present locally.
    import subprocess
    res = subprocess.run(
        ["docker", "images", "--format", "{{.Repository}}:{{.Tag}}"],
        capture_output=True, text=True, timeout=10,
    )
    local_images = {line.strip() for line in res.stdout.splitlines() if line.strip()}

    chosen: list[str] = []
    for inst in data["instances"]:
        image = f"jefzda/sweap-images:{inst['dockerhub_tag']}"
        if image in local_images:
            chosen.append(inst["instance_id"])
        if len(chosen) >= 5:
            break

    if len(chosen) < 1:
        print("[pro-smoke] FAIL: no Pro images present locally; cannot run smoke.")
        print(f"[pro-smoke] Pull at least one image (see docs/audits/pro_image_inventory.md).")
        return 2

    if len(chosen) < 5:
        print(f"[pro-smoke] WARN: only {len(chosen)}/5 Pro images present locally; "
              f"running partial smoke.")

    views = load_pro_views(instance_ids=chosen)
    print(f"[pro-smoke] loaded {len(views)} Pro views")

    rows: list[dict] = []
    overall_t0 = time.perf_counter()

    for v in views:
        print(f"[pro-smoke] {v.instance_id} ({v.repo}) image=jefzda/sweap-images:"
              f"{v.dockerhub_tag[:40]}…", flush=True)
        t0 = time.perf_counter()
        try:
            with Sandbox(v, max_observation_chars=32_000_000) as sb:
                result = run_stage_1b_retrieval(
                    v, sb,
                    embedding_service=None,
                    include_traceback=False,
                    skeleton=None,
                )
            elapsed = time.perf_counter() - t0
            top_paths = [c["file_path"] for c in result.candidates[:5]]
            rows.append({
                "instance_id": v.instance_id,
                "repo": v.repo,
                "dockerhub_tag": v.dockerhub_tag,
                "n_files_indexed": result.n_files_indexed,
                "n_candidates": len(result.candidates),
                "top5_paths": top_paths,
                "duration_s": elapsed,
                "error": None,
            })
            print(f"[pro-smoke]   OK n_indexed={result.n_files_indexed} "
                  f"candidates={len(result.candidates)} "
                  f"top1={top_paths[0] if top_paths else 'n/a'} "
                  f"({elapsed:.1f}s)")
        except Exception as exc:
            elapsed = time.perf_counter() - t0
            err = f"{type(exc).__name__}: {exc}"
            rows.append({
                "instance_id": v.instance_id,
                "repo": v.repo,
                "dockerhub_tag": v.dockerhub_tag,
                "n_files_indexed": 0,
                "n_candidates": 0,
                "top5_paths": [],
                "duration_s": elapsed,
                "error": err,
            })
            print(f"[pro-smoke]   FAIL {err} ({elapsed:.1f}s)")

    total = time.perf_counter() - overall_t0
    n_ok = sum(1 for r in rows if r["error"] is None)
    print(f"[pro-smoke] {n_ok}/{len(rows)} OK in {total:.1f}s")

    # Render audit doc.
    OUT.parent.mkdir(parents=True, exist_ok=True)
    out: list[str] = []
    out.append("# SWE-bench Pro 5-instance retrieval smoke")
    out.append("")
    out.append(
        "Generated by `scripts/pro_retrieval_smoke.py`. Validates the Pro "
        "dataset adapter (Step 5) end-to-end:"
    )
    out.append("")
    out.append(
        "1. `harness.dataset.load_pro_views` projects Pro rows into "
        "`InstanceView` (with `dockerhub_tag` populated)."
    )
    out.append(
        "2. `harness.sandbox.Sandbox` starts the Pro image "
        "`jefzda/sweap-images:{dockerhub_tag}` (vs. Verified's "
        "`swebench/sweb.eval.x86_64.*`)."
    )
    out.append(
        "3. `harness.retrieval.run_stage_1b_retrieval` reads `/testbed`, "
        "indexes BM25 across 3 query strategies, returns candidates."
    )
    out.append(
        "4. The contamination firewall does NOT fire — Pro's lowercase "
        "`fail_to_pass` / `pass_to_pass` / `patch` / `test_patch` fields "
        "are dropped by the projection whitelist exactly as Verified's are."
    )
    out.append("")
    out.append(f"- **Instances:** {len(rows)}")
    out.append(f"- **OK:** {n_ok}/{len(rows)}")
    out.append(f"- **Wall-clock:** {total:.1f}s")
    out.append("")

    out.append("## Per-instance results")
    out.append("")
    out.append("| Instance | Repo | n_indexed | n_candidates | duration | top-1 path |")
    out.append("|---|---|---|---|---|---|")
    for r in rows:
        top = r["top5_paths"][0] if r["top5_paths"] else "—"
        marker = "✓" if r["error"] is None else "**FAIL**"
        out.append(
            f"| `{r['instance_id'][:60]}…` | {r['repo']} | "
            f"{r['n_files_indexed']} | {r['n_candidates']} | "
            f"{r['duration_s']:.1f}s | `{top}` {marker} |"
        )
    out.append("")

    failed = [r for r in rows if r["error"]]
    if failed:
        out.append("## Failures")
        out.append("")
        for r in failed:
            out.append(f"- `{r['instance_id']}`: `{r['error']}`")
        out.append("")

    out.append("## Acceptance")
    out.append("")
    if n_ok == len(rows) and rows:
        out.append(
            "**PASS** — the Pro adapter (Step 5) is live: dataset projection, "
            "Sandbox image override, and BM25 retrieval all work on Pro data "
            "with no code changes to the retrieval pipeline."
        )
    else:
        out.append(
            f"**PARTIAL** — {n_ok}/{len(rows)} instances passed. See "
            "Failures above; investigate before declaring Step 5 done."
        )
    out.append("")

    OUT.write_text("\n".join(out))
    print(f"[pro-smoke] wrote {OUT.relative_to(PROJECT_ROOT)}")
    return 0 if n_ok == len(rows) and rows else 2


if __name__ == "__main__":
    sys.exit(_smoke_5_instances())
